about/fellowship/index.html
[Preview the changes here](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/fellow-disambig/about/fellowship/)
This resurrects the /about/fellowship page and provides a path for multiple audiences to relevant fellowship pages (i.e. funnels government partners to /governments/fellowship to signal their interest in the fellowship, sends potential fellows to /geeks/fellowship-apply to say they're interested in being a future fellow).
@ZoeBlumenfeld is reviewing content and will give :+1: when it's good to go.
=> Create fellowship disambiguation page

.htaccess, .test-httpd.py
The /codeacross/ redirect went to the page for last year. Updates so codeforamerica.org/codeacross will redirect this year's page.
Tested locally with .run-httpd and it works.
@migurski please idiot check and merge.
(/cc @mollymcleod who asked for this update)
=> Update redirect for /codeacross/ > /events/codeacross-2015

_includes/meta-header.html, fragments/global-metadata.html
I'm trying to get the blog to start serving up nice metadata for social sharing/linking. I'm going to serve the static metadata file so I can pull its contents for non-article pages on the blog.
Page will serve from /fragments/global-metadata.html
=> Serve static metadata for the blog

.htaccess, .test-httpd.py
codeforamerica.org/health ---> codeforamerica.org/our-work/focus-areas/health
cc @alanjosephwilliams
=> Add health redirect, fix talent redirect trailing slash

_config.yml, _includes/meta-header.html
Before, og:url always pointed to codeforamerica.org/. This majorly messed up the way Facebook and others read our metadata (every page posted in social was supposedly our root).
This should fix that problem.
=> Update metadata so every page gets a custom og:url

_config.yml
When we force our metadata og:url to be https://codeforamerica.org/*, Facebook gives us this error when it tries to read the metadata off our pages:
```
Curl Error : SSL_PEER_CERTIFICATE SSL: no alternative certificate subject name matches target host name 'codeforamerica.org'
```
Trying to go with http for now for social metadata.
=> In social metadata, use http

script/home-story.js, stories.js
This PR updates code and stories for the hero unit at the top of the homepage.
To preview, [open this link and keep refreshing](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/add-new-stories/) -- stories are loaded randomly.
I've rewritten the `home-story.js` function a bit to have it add a Google Analytics tracking event on a button or headline click. We can track engagement on the stories.
I've also added new stories for Health (cc @alanjosephwilliams), Summit (cc @mattboitan0), Talent (cc @lanebecker).
=> Update stories script to produce a GA tracking event, add new stories

our-work/focus-areas/health/index.html, our-work/focus-areas/index.html
- Updates to `our-work/focus-areas/health`
- listed all health domain projects, in the `teaser-app no-logo` pattern which already was in use on the focus-area umbrella page.
- Made some copywriting and layout adjustments as a result
- Updates to `our-work/focus-areas`
- created links to the health focus area page in sensible places
- removed mention of California Healthcare Foundation since they are now referenced with other major supporters on the health focus area page. 
- Added a section heading for the project patterns, since it was wanting.
=> Updates to ../focus-areas and ../focus-areas/health

_includes/global-footer.html, _layouts/default.html, _layouts/speakers.html, index.html, stylesheets/staging.scss
We're serving up the global-footer to other sites. I'm removing the email signup from it for now to address some problems in #936. More updates needed in the future to make this a modular piece of code that can be dropped into sub-sites (like /blog/ and /brigade/).
=> Remove email signup from global footer

our-work/data-formats/openreferral/index.html
I updated the links to v0.9, but we're about to move to 1.0. 
I thought about linking just to [the repo](https://github.com/codeforamerica/OpenReferral/), which would future-proof against further iterations. but that is going to confuse anyone who is expecting the spec and not used to Github. Suggestions welcome.
=> Updated spec links (to Google docs)

_includes/people/david-leonard.html, about/team/index.html
Adds me to the staff page, updates content in my bio.
* Preview [/people/david-leonard](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/update-david-bio/people/david-leonard/)
* Preview [/about/team](http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/update-david-bio/about/team/)
/cc @Jaime-Alexis or @ZoeBlumenfeld - please review the words in my bio? Thanks.
=> Add David to staff page, update bio

_includes/nav.html, _layouts/default.html, signup/index.html
First step to making this a real thing. When CfA people are out and about, they can send people to http://codeforamerica.org/signup to sign up directly for our mailing list.
Link to preview: http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/email-signup-page/signup/index.html
cc @Jaime-Alexis @ZoeBlumenfeld for review. 
cc @pahlkadot, who requested.
=> Add new signup page and some patterns for that style of header, will need refactor later

_includes/people/alex-soble.html, _includes/people/amir-hadjihabib.html, _includes/people/andrew-schneider.html, _includes/people/ben-golder.html, _includes/people/ben-smithgall.html, _includes/people/chris-reade.html, _includes/people/emma-smithayer.html, _includes/people/ernie-hsiung.html, _includes/people/grant-smith.html, _includes/people/imanol-aranzadi.html, _includes/people/jazmyn-latimer.html, _includes/people/jennings-hanna.html, _includes/people/laura-ellena.html, _includes/people/mari-muraki.html, _includes/people/mathias-gibson.html, _includes/people/natasha-fountain.html, _includes/people/nikki-zeichner.html, _includes/people/patrick-hammons.html, _includes/people/sam-matthews.html, _includes/people/shelly-ni.html, _includes/people/sophia-dengo.html, _includes/people/tiffany-andrews.html, _includes/people/william-tyner.html, _includes/people/yaniv-zimet.html
Each fellow now has a team name with a link back to their city. Fixes #919.
=> Add team name tags to 2015 fellow bios/cards

about/team/index.html
we don’t appear to use the phrase “open positions” on the job page, so
a tweak to change the button copy to “Job Opportunities”
=> tweak copy for jobs button

.travis.yml
Attempted quick fix to solve our breaking build on Travis (see https://travis-ci.org/codeforamerica/codeforamerica.org/builds/57733171) by specifying ruby 2.2.0 before installing jekyll.
Long term, it seems like we might want to introduce bundler and specify which ruby we want to use in a Gemfile. Then we can run jekyll with `bundle exec jekyll <blah>` locally, during testing and on production and keep a consistent environment.
(ping @migurski ^ thoughts on that longterm?)
=> When building on Travis, specify ruby 2.2.0

governments/principles/government-technology/index.md
A misspelling, and an inconsistent use of license/licence.
=> Two typos in principles for gov tech

_includes/apps/cityvoice.html, _includes/apps/promptly.html, _includes/apps/recordtrac.html
It’s our understanding that PostCode is no longer delivering CityVoice, Promptly, or RecordTrac.
=> Removed reference to PostCode to reflect their new strategy

.htaccess, .test-httpd.py
codeforamerica.org/apply will redirect to the fellowship-apply page.
=> Reinstate redirects for /apply

summit/propose/index.html
The link needed a protocol to work -- as it is, it takes people to `https://www.codeforamerica.org/summit/propose/www.codeforamerica.org/governments/principles/`, which is a 404.
Note I specified the `https://` protocol, which works and throws no errors. That can be adjusted if not desired.
=> Fix broken link from 2015 Summit proposal to 21st Century Principles

summit/sponsor/index.html
Adds some pull-out numbers to the sponsor page to give potential sponsors an idea of the scale of the event.
@Jaime-Alexis could you review and let me know if these are the right numbers / if we should add more numbers?
=> Add numbers to sponsor page

_includes/apps/cityvoice.html
The row currently contains a broken /td> tag, so it needs improvement.
Outright removal matches the style of e.g. adopt-a-hydrant page.  The CTA at the bottom of the table has the trial information.
=> Removing stray table row

.htaccess
The awards site is on a subdomain (it's built separately from our main site). Let's redirect /awards/ just in-case someone tries to find it without a subdomain.
=> Add /awards/ redirect to awards.cfa.org

logos/index.html
Use of grey/gray inconsistent on this page, so I thought I'd change it. I moved gray -> grey because that's what the urls + title were.
=> Grayscale -> greyscale

_includes/global-footer.html, _includes/nav.html, stylesheets/staging.scss
We're changing up the top of the nav. (Description in the title of this PR.)
First step of this executed on the codeforamerica/pattern-library#8, which pulls our nav items closer together so they don't look wonky as the viewport shrinks. In #1207, we move our site to v3 of the pattern library so we can get these changes on codeforamerica.org.
This is the last step. We're banishing the black bar nav, moving blog into regular nav, moving search into footer.
There's still two issues to deal with going forward:
* We still need an empty .nav-global-primary container because of the wonky nav collapse function in global.js. Something to fix in the future.
* We have all kinds of code hanging around calling or not calling nav-global-primary in frontmatter around the site. This needs to be cleaned …
=> Remove black bar in nav, but Blog in main nav, move search to footer

index.html
This should be a link. Now it is. :)
=> Add link to blog in Blogging for America header on homepage

_includes/nav-summit-2015.html, summit/index.html
Hi @davidrleonard:
Molly and I updated the headline on the Summit landing page to match the correct messaging. Also changed the 2014 Summit Videos link to go to YouTube instead of the Library because the Library looks like poo poo.
Please check and merge. thanks!
=> Update headline, Add YouTube link

_includes/email-signup-form.html, _includes/email-signup-modal.html, _layouts/default.html, our-work/focus-areas/economic-development/index.html, script/email-signup.js, signup/index.html
We have a need to allow for complex customizations in our email signup modal. As we bring focus-area specific mailing list groups online, each one will need custom signup options in various places throughout the site.
Here are the new choices for launching an email signup flow:
You can spawn an email signup modal with whatever data by creating an anchor link (or button, or any other clickable thing) with the correct data attributes.
Here's an example from the Economic Development page:
```
<a href="#" class="button button-l button-bold" data-email-signup-button="true" data-email-headline="I'm interested in Economic Development" data-email-description="Want to learn more about what Code for America is doing to promote inclusive economic growth? Join our email list help inform Code for …
```
=> Allow email signup dialog to be customized

_includes/global-footer.html, _includes/nav-speakers.html, _includes/nav-summit.html, _includes/nav.html, _includes/summit-footer.html, governments/atlantis/index.html, governments/emeraldcity/index.html, peer-network-training/fakefolder/index.html, summit/2014/submit/index.html, valentine/testimonial/index.html
#1434 points out we don't have alt text on our header/footer logos. Bad accessibility, us. :( This PR fixes that by adding appropriate alt text. 
Thanks @bobprokop for pointing this out.
=> Add logo alt text

products/citizen-engagement.html, products/free.html, products/local-service.html, products/paid.html
Fixes issue #790. These buttons weren’t hooked up to any JavaScript and
were causing the page to jump back to the top when clicked.
=> Remove "Load More" Buttons - #790

robots.txt
The marketing team is concerned that the many pages of the archive site are dominating Code for
America search results. It was decided that we'll take some steps to prevent the archive sites from
showing up on search engines, especially on Google. This adds a robots.txt file with the instruction for
bots to not crawl the pages of the archive site.
=> Stop search engines from crawling the archive site by adding robots.txt
