.run-httpd.py

Fixing Apache run on Mac OS X 10.10.

Add conditional to check if MpmEvent exists

---

_includes/people/molly-mcleod.html
about/team/index.html

I'm on the team now!
@ZoeBlumenfeld review content/quick copy edit for me?
@davidrleonard check code.

Update Molly's people page and added her to team page

---

governments/2015-cities/index.html

Added the focus areas to test visitor engagement.

Added focus areas to 2015 cities

---

index.html

Let's get a new blogpost up there, the old one is stale.
@ZoeBlumenfeld or @Jaime-Alexis please check and merge.

Change out homepage blog post to 2014 brigade year in review

---

_includes/people/jacob-solomon.html

@davidrleonard LMK if I missed anything.

update Jacob's speaker info

---

_includes/people/hannah-young.html

I updated my speaker bio and added a video.

Updated speaker page with new information

---

governments/fellowship/index.html

Add link to the FAQ from the Governments/Fellowship page.

Add link to fellowship FAQ

---

.htaccess
.test-httpd.py

Redirect /fellowship to /about/fellowship

---

_includes/blogposts.html

Pull in the image dynamically.

Update fellowship page blogs

---

index.html

Updates homepage blog post to Mai-Ling's post. Adds GA event tracking on the buttons.
/cc @Jaime-Alexis

Update blog post on homepage, add GA tracking

---

stories.js

Hi @davidleonard @Jaime-Alexis , updated link in stories. Please check and merge.

Update health page link

---

_includes/apps/text-my-bus.html

Fix fellowship year, add some more recent info, and add a quick mention of the API component.

Update TextMyBus app info

---

our-work/data-formats/openreferral/index.html

I think you'll want to upload those images rather than pulling from the source. But I have failed to learn how to do that (and tried for like an hour last time).

Updated ecosystem / partners

---

our-work/data-formats/openreferral/index.html

Very slight tweak to header. I forget whether we discussed a more dramatic change... i think I am stuck on uncertainty about whether this page should really just be for the format (as per its category) or actually should promote Open Referral as an initiative.

Tweak header text and action buttons

---

our-work/data-formats/openreferral/index.html

I removed the request for comment text, and left that section blank for now. 
Also tweaked the form language.
I hope i didn't break anything.

Edited Call to Action section.

---

our-work/data-formats/openreferral/index.html

Deleted Core Team, moved Jack to Advisors

---

governments/principles/open-data/index.html

trying to fix layout problems with open data playbook

open data playbook layout

---

_includes/apps/localdata.html

We'e updated the LocalData description to more accurately reflect our work.

Update LocalData description

---

_includes/people/preston-rhea.html

Updated the title and job description. cc @cbracy @davidrleonard

updated Preston's title to civ engagment

---

forms/governments/fellowship/apply/index.html
governments/fellowship/index.html

Link off-site to the form, as it's creating formatting issues as an embed right now.

Fix government fellowship application form

---

_includes/apps/balance.html

h/t to @MarcBrent for the heads up.

update list of active balance states

---

.htaccess
about/values/index.html

Fix broken link to principles (formerly capabilities) found by @pahlkadot.

Fix broken gov link

---

jobs/index.html

Add Talent Director

---

jobs/index.html

Add Sr Software Arch

---

forms/fellowship/become-a-fellow/index.html
geeks/fellowship-apply/index.html

Updated copy to include:
* Application period: 5/15-6/15
* Program duration and location
* Add "Code for America Fellowship" for SEO
@davidrleonard for code @Jaime-Alexis for copy

Fellowship update 4.1

---

jobs/index.html

Add HR Manager

---

forms/fellowship/become-a-fellow/index.html
geeks/fellowship-apply/index.html

@Jaime-Alexis please review updated copy.

Fellowship update 4.7

---

speakers/catherine-bracy/pycon.html

removed sxsw tracking and replaced with pycon

update fellowship link

---

geeks/index.html

Hey @Jaime-Alexis and @mollymcleod 
I've started to redo the /geeks page and it could use some love. http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/geeks-refresh/geeks/
Have any suggestions? I really miss the Geek of the Week from the [live version](http://codeforamerica.org/geeks).

Refreshed the /geeks page

---

jobs/index.html

Removed UX plus senior architect

Removed jobs

---

index.html

Also, link out to HTTPS urls where available

Use HTTPS resources - #529

---

index.html

@Jaime-Alexis please review copy for homepage update @davidrleonard for code

add new blog to homepage

---

supporters/index.html

Add in major benefactors to supporters page with @mattboitan0.

Add in major benefactors

---

summit/sponsor/index.html

Linked to Google Doc version of prospectus rather than uploading a PDF - civic tech win!

added link to prospectus

---

governments/principles/engagement/index.html

Standard ready to publish @dschrimmer

Incorporated edits from @cbracy

---

governments/principles/engagement/index.html

Excellent cross-team collaboration between Content and Communities team! 
High fives and :+1: to @prestonrhea and @cbracy .

Publishing the engagement standard

---

governments/principles/engagement/index.html

minor text edit

---

our-work/data-formats/openreferral/index.html

Site's down, dunno when it will be back up.

Remove Edori from 'apps and outcomes'

---

script/global.js

In the spirit of fellow recruitment season, this adds a little script that console.logs() a call to apply for the fellowship for people inspecting our code.
As far as I can tell, this creates very negligible performance debt. I'm also checking to make sure window.console exists, so this shouldn't create an undefined function in IE9 and before, where the console object isn't defined unless developer tools are open.

Recruitment: JavaScript console edition

---

our-work/data-formats/openreferral/index.html

Hi - I got this image from Phil and added it in there - http://dropbox.ashlock.us/photos/profile/philipashlock-small-square-ds.jpg - but don't know if you want to upload it and/or edit?

Added advisor - Phil Ashlock

---

summit/propose/index.html

- added where and when
- added free ticket to top paragraph
@davidrleonard check code and merge, please.

update copy for SEO

---

geeks/fellowship-apply/index.html

Added application timeline graphic and apply button, small copy edits

Added graphic and content tweaks

---

_includes/people/alan-williams.html
_includes/people/alex-tran.html
_includes/people/ashley-meyers.html
_includes/people/bob-sofman.html
_includes/people/dana-oshiro.html
_includes/people/dave-guarino.html
_includes/people/erica-kwan.html
_includes/people/jacob-solomon.html
_includes/people/lauren-reid.html
_includes/people/mettabel-law.html
_includes/people/michael-santus.html
_includes/people/molly-mcleod.html
_includes/people/ron-bouganim.html

Cleanup staff

---

_includes/nav.html
geeks/index.html
governments/fellowship/index.html
governments/index.html
index.html
stories.js

Many small fixes (issues referenced in the commit logs) to Fellowship pages.

Fellowship fixes

---

index.html

The codes seem to be specific to each account, so this just works for me. I'll see if it can be shared.

Add google webmaster verification code

---

_includes/footer-scripts.html

This: https://support.google.com/analytics/answer/2558867?hl=en&utm_id=ad

GA enhanced link attribution

---

_includes/apps/cityvoice.html
apps/cityvoice/index.html

Fixes to the layout and markup for CityVoice. cc @jmadans

Cityvoice fixes

---

_includes/footer-scripts.html
_layouts/focus-area.html
_layouts/speakers.html
forms/fellowship/become-a-fellow/index.html
forms/fellowship/become-a-fellow/submitted.html
forms/speakers/request/index.html
geeks/fellowship-apply/index.html
index.html

A redesign of the fellowship form to a simpler format, a new dynamic next step page that pushes users on to the next application with appropriate data, and new embeds of our fellowship marketing video.
fyi @Jaime-Alexis

Fellowship application updates

---

governments/index.html

Deleted out of date logos

---

_includes/nav-summit-2015.html
_includes/nav-summit.html

* In the 2014 Summit page, fix the navigation to point to the correct 2014 pages
* Add a link to 2014 summit videos the 2015 summit nav

2014 summit tweaks

---

_includes/people/efrem-bycer.html

@davidrleonard Add photo and please review code.

Add Efrem Bycer bio page on website

---

_includes/people/dave-guarino.html

- Closes https://github.com/codeforamerica/health/issues/168 
- Updates my bio text and adds a different picture

Update Dave bio

---

_includes/people/jessica-silverman.html

This is a work in progress. I need to add my short and long bios. Will do in the next few days! :+1: 
@davidrleonard - would you please add my photo!

Create Jessica Silverman bio page

---

_includes/people/___-___.html
_includes/people/efrem-bycer.html
_includes/people/jessica-silverman.html

Forgot to add bios for these two as we created their new bios.

Add titles for new staff members

---

_includes/people/mischa-byruck.html

@davidrleonard please review the code.

Create mischa byruck page

---

geeks/fellowship-apply/index.html

@davidrleonard made style updates to virtual office hrs buttons and added the info session links

Fellowship events

---

geeks/fellowship-apply/index.html

@Jaime-Alexis I made small copy edits based on a conversation I had w/ Kevin. Let me know what you think + merge if appropriate.

Fellowship update 6.17

---

_includes/people/jason-denizac.html

Just keeping things current and up-to-date!

Update links on Jason Denizac people page

---

geeks/fellowship-apply/index.html

@davidrleonard : I updated copy to reflect deadline. Please check code and merge, thanks!

Fellowship update 7.13

---

index.html

Call out to our /blog/ API and dyanamically update the blog on the homepage, fallback to the static post that's already there if there is no JS.
Closes #1183.

Dynamically update homepage blogpost

---

about/index.html
forms/fellowship/become-a-fellow/index.html
geeks/fellowship-apply/index.html
geeks/index.html
governments/fellowship/index.html
governments/index.html

This should be pushed live Thursday morning early am or Wednesday night after midnight. 
Thanks!
G

Fellowship app closed

---

jobs/index.html

Removed HR Manager

---

jobs/index.html

Removed Dev Asst

---

_layouts/default.html
_layouts/focus-area.html
_layouts/markdown.html
_layouts/pn-training.html
_layouts/principles-standard.html
_layouts/resource.html
_layouts/speakers.html
_layouts/summit-2014.html
_layouts/summit-2015.html

We're introducing new patterns and updating old ones in v3 of the pattern-library. I'm bumping up so we call v3 of our stylesheets on all layouts across the site.

Bump - have all layouts call version 3+ of the pattern-library

---

stories.js

Hi @davidrleonard. Could you check the code and merge? We probably need to add more stories, @Jaime-Alexis. Perhaps the blog about how to deploy 3 CfA products? In the meantime, let's delete these from the homepage.

remove old stories

---

_includes/email-signup-modal.html
our-work/focus-areas/economic-development/index.html
script/email-signup.js

Create new signup for Economic Development email list

---

_layouts/resource.html
playbooks/technology-procurement/background/index.md
playbooks/technology-procurement/delivering-digital-services/index.md
playbooks/technology-procurement/digital-service-rfps/index.md
playbooks/technology-procurement/index.md
playbooks/technology-procurement/organize-government-for-digital-services/index.md

add status=alpha frontmatter tag
add feedback-name and feedback-email frontmatter tags to build email
address for feedback
display alpha banner with feedback email address
tidied up resource_index = true conditionals
Display quality survey on all pages

resource template update

---

jobs/index.html

Ahh, I didn't Pull Request last time on this one...I deleted the line with the Executive Coordinator role to remove it from our site.  ok?

Removed Executive Coordinator role

---

jobs/index.html

Made a copy of Content Community Manager position and added a line - hopefully this will add this to our job board?
Thanks!

Added Director of Communications & Engagement line above all other jobs

---

jobs/index.html

Removed "Content & Director" to simply "Director of

Urgent? Typo on job page

---

jobs/index.html

Plus added another blank line above the first job listed.  Not sure if that's why my first Pull Request didn't work?

Added Brigade Development Manager position

---

jobs/chime/index.html

In an attempt to make my emails maximally appealing, I've created a specific codeforamerica.org URL for the Chime job.

attempting to create a Chime-specific jobs page

---

summit/index.html

Summit@ wasn't on the Summit page

Add summit email

---

_data/summit_supporters.json
media/images/summit/2015/logos/GT14 print logo 4c_4x4.eps

@davidrleonard could you take a look at the code and merge? thanks!

add govtech logo and link

---

jobs/index.html

Hi Dave, 
Please update our job board with the following revised title:
Director, Communications & Engagement to
Focus Area Director: Communications & Engagement
Thanks!

Change title from Dir, Comm & Eng to Focus Area Dir: Comm & Eng

---

jobs/index.html

Updated the Jobs index - changed from "Senior Engineer" to Engineer, Digital Front Door.
I noticed a Chime Engineer file next to Index there - not sure if I needed to make a change there too?
Thanks!
cc davidrleonard

Changed Engineer, Chime to Engineer, Digital Front Door

---

summit/index.html

Reverts codeforamerica/codeforamerica.org#1331

Revert "Adding facebook pixel for conversion tracking."

---

jobs/index.html

Deleted Brigade Coordinator position - yay!
cc/daveleonard

Close Brigade Coordinator position

---

_includes/people/brenda-stone.html

waiting on photo before this is ready
//cc @davidrleonard

Added my bio

---

jobs/index.html

Brenda stone patch 12

---

jobs/index.html

Add Accountant position AND
Remove Content & Community Manager/Health and Human Services position

Job Posting changes: CCM and Accountant

---

jobs/index.html

Another new job - thanks Dave!

Add Customer Success Specialist position

---

_includes/people/alan-williams.html
_includes/people/david-leonard.html
_includes/people/jacob-solomon.html
_includes/people/jenny-montoya-tansey.html
_includes/people/molly-mcleod.html
_includes/people/rebecca-coelius.html
about/team/index.html
forms/speakers/request/index.html
our-work/focus-areas/health/index.html
speakers/index.html
speakers/rebecca-coelius/index.html

Remove Rebecca from staff page, remove references to her as a speaker, add 'Former' to her titles on people page
:cry:

Bye rebecca :(

---

jobs/index.html

Updated Customer Service Specialist to Customer Service Coordinator
Removed (filled!) Director, Health & Human Services position

Title Correction and New Job

---

_includes/people/william-pietri.html
about/team/index.html
people/william-pietri/index.html

As requested, @davidrleonard. Thanks!

Adding myself to the website

---

jobs/index.html

Removing Customer Success Specialist job for now - to repost sometime after Summit
thanks!

Remove Customer Success Specialist

---

governments/practices/index.html

Updated the header image — Jen wanted a different one

changed image

---

jobs/index.html

We are revising the role...will post a revision after Summit...
Thanks!

Remove Brigade Content Manager

---

jobs/index.html

Hi Dave,
Please remove the Brigade Development Manager position - it's been filled!  
Thanks!

Remove Brigade Development Manager position

---

stories.js

@davidrleonard could you review and merge while you're update the page w/ videos?
Best,
Zoe

update homepage story

---

_includes/people/monique-baena-tan.html

@davidrleonard please review my page! 
I'll have it done by Wednesday

created my bio page! WIP

---

governments/practices/data-driven/index.html
governments/practices/design/index.html
governments/practices/engagement/index.html
governments/practices/open/index.html
governments/practices/procurement/index.html
governments/practices/team-building/index.html

took off superfluous numbered titles on practice pages

Removing titles

---

governments/practices/data-driven/index.html
governments/practices/design/index.html
governments/practices/engagement/index.html
governments/practices/open/index.html
governments/practices/procurement/index.html
governments/practices/team-building/index.html

bringing back the right headers without numbered practices.

Edit titles

---

_includes/people/chi-offomah.html

A year before joining Code for America in August 2015, Chi was finishing up her public health degree and soaking up the sun in Tucson, Arizona. Her social justice streak led her to found the Tucson chapter of the international street harassment group Hollaback!, where she got her hands deep into community activism. She joined LGBTQ mental health non-profit the UCSF Alliance Health as a communications intern and fell in love with all things fundraising. When she’s not in the office, Chi's hunting down sun, food, and fun!

Creating Bio

---

_includes/people/alexis-charles.html

created page still need to add bio and photo

Created a bio for myself (WIP)

---

jobs/index.html

this position is on hold for now

Remove Community Platform Manager job

---

jobs/index.html

Both Sr Engineer and Communications & Engagement Director have been filled.  Thanks for removing these for me! -brenda

Remove Engineer and Focus Area Director jobs

---

events/codeacross-2016

created codeacross 2016 page to allow brigades to sign up to organize
@davidrleonard @ondrae let me know if you have questions, especially with the link to the Typeform. Wasn't sure how to do that part. Thank you!

Codeacross-2016

---

jobs/index.html

Remove Talent Director role for now -- it's on hold.  thanks!

Remove Talent Director role

---

jobs/chime/index.html

This job is filled. I'm leaving the page up but unlinked so that it can be used as an example for an upcoming blog post on hiring.

job is filled

---

jobs/index.html

Hi David,  Please help me post this asap...I forgot to create a pull request for this before the break!
thanks so much!
-brenda

Add Mgr Corp Sponsorships and Donations job

---

events/codeacross-2016/index.html

updated workshops and resources

---

jobs/index.html

Removing: Lead Engineer, Lead Designer (both filled) and Product Manager (strong candidates)

Remove Safety & Justice positions

---

jobs/index.html

Pls post Grants Administrator position

---

jobs/index.html

Renamed from Manager, Corp Sponsorships and Donations to Manager, Corporate Events Sponsorships

Update Corporate Sponsorship role

---

events/codeacross-2016/index.html

@ZoeBlumenfeld @davidrleonard - codeacross event URLs added. thank you!

added URL links for events in cities

---

events/codeacross-2016/index.html

updated resources and event URLs

---

events/codeacross-2016/index.html

added San Jose, Miami and Chicago

---

events/codeacross-2016/index.html

updated links and added cities

---

events/codeacross-2016/index.html

added Denton

---

events/codeacross-2016/index.html

Added San Diego

---

events/codeacross-2016/index.html

Added Ponta Grossa, Brazil

---

practices/open/open-data/index.html

add OpenDataSoft

---

_includes/global-footer.html

remove defunct info@ from footer

remove info@ from footer
